# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog-blog - work-work bloggen
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog av folkene på work-work. Her skriver vi om spill, hacks og ting som
  opptar oss. Dette er bakomfilmen om work-work, historiene om det vi lager.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog-blog.no" # the base hostname & protocol for your site
twitter_username: WorkWorkTrd
github_username:  workwork

# Build settings
markdown: kramdown
